platform :ios, '8.4'
pod 'MBProgressHUD', '~>1.0.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'MD5Digest','~>1.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.8.0' 
pod 'Masonry', '~> 1.0.0'
pod 'MJRefresh' ,'~>3.1.0'
pod 'YYKit', '~>1.0.1'
pod 'DZNEmptyDataSet'
pod ‘UMengUShare/UI’
pod ‘UMengUShare/Social/Sina'
pod ‘UMengUShare/Social/WeChat'
pod ‘UMengUShare/Social/QQ'
